### ISSUE TITLE
Inappropriate japanese

### ISSUE THREAD

**Issue by suzukana** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6404] opened 2020-12-23 03:40 UTC
[フィードバックをこちらに入力してください]
" 管理センターには、にアクセスでき https://admin.microsoft.com ます。 " is an incorrect Japanese sentence.
The correct sentence is "https://admin.microsoft.com から管理センターにアクセスできます。".
 
---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 3b51b67a-d89c-723f-3520-87cb2dc93b90
* Version Independent ID: 78d10cbc-d75b-2b02-d49c-2c3fe1579807
* Content: [Microsoft Teams 管理センターでチームを管理する - Microsoft Teams](https://docs.microsoft.com/ja-jp/microsoftteams/manage-teams-in-modern-portal#feedback)
* Content Source: [Teams/manage-teams-in-modern-portal.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-teams-in-modern-portal.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment] 2020-12-26 02:40
@suzukana  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
@Officeglobal Could you please help with this issue? Thanks!

**Comment by TinaMcN** [comment] 2021-04-05 23:37
@suzukana thanks for reporting this issue.  It appears to be caused by machine translation.  I sent the article to be human translated and it should be completed in approx 3 days.

**Comment by TinaMcN** [comment] 2021-04-08 16:29
@suzukana the article is now human translated.   The sentence is now "お客様はhttps://admin.microsoft.comにて、管理センターにアクセスできます。" which is different from your suggestion.  Does it look ok and if so can you please close this issue?  Thanks again for letting us know about this problem.

**Closed** 2021-05-05 04:24 UTC
