### ISSUE TITLE
Mistranslation in a Japanese article

### ISSUE THREAD

**Issue by kefujino** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6748] opened 2021-03-02 02:39 UTC
Hello, this feedback is translation bug for Japanese article.

English
https://docs.microsoft.com/en-us/microsoftteams/non-standard-users?source=docs#install-update-and-delete-for-guest-users

> Guests don't have access to the Teams app store.

Japanese
https://docs.microsoft.com/ja-jp/microsoftteams/non-standard-users?source=docs#install-update-and-delete-for-guest-users

> ゲストは Teams アプリ ストアにアクセスできます。

![image](https://user-images.githubusercontent.com/13634805/109588156-a7a05b80-7b4b-11eb-85f7-fbc47832339d.png)

The above translation means the opposite. I suggest that you fix it as follows:

> ゲストは Teams アプリ ストアにアクセスでき**ません。**

Thank you!

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0735d322-f6f5-7cc8-9994-1420e3fb7baa
* Version Independent ID: f9b25b51-eb9c-63fa-b30e-e1490c8d31b6
* Content: [Teams apps behavior for non-standard users - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/non-standard-users?source=docs)
* Content Source: [Teams/non-standard-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/non-standard-users.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment] 2021-03-02 23:45
@kefujino  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TinaMcN** [comment] 2021-04-08 16:57
@kefujino thank you for reporting this issue which is caused by a machine translation bug which is being investigated.  I sent this article to be human translated and it should be completed in 3 business days.
@scanum can you please assign any localization issues to me, OfficeGlobal isn't actively monitoring issues currently.

**Comment by TinaMcN** [comment] 2021-04-13 16:38
@kefujino the article has been human translated, can you please close it if it looks ok now?

**Closed** 2021-05-05 04:26 UTC
