### ISSUE TITLE
Assign a custom app permission policy to users in a group

### ISSUE THREAD

**Issue by Naz9mm** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3263] opened 2019-10-23 16:17 UTC
Not sure if its just me but the 3rd powrshell command below - fails

$members | ForEach-Object { Grant-CsTeamsAppPermissionPolicy -PolicyName "HR App Permission Policy" -Identity $_.EmailAddress}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b51eda6c-168c-7d99-7cc1-992b3d8feef2
* Version Independent ID: 118a1b8f-f4b7-a778-70b1-d3161fc548ab
* Content: [Manage app permission policies in Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/teams-app-permission-policies?WT.mc_id=TeamsAdminCenterCSH#feedback)
* Content Source: [Teams/teams-app-permission-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-app-permission-policies.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by Naz9mm** [comment] 2019-10-23 16:20
error message
Cannot validate argument on parameter 'Identity'. The argument is null or empty. Provide an argument that is not null
or empty, and then try the command again.
    + CategoryInfo          : InvalidData: (:) [Grant-CsTeamsAppPermissionPolicy], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Rtc.Management.AD.Cmdlets.AssignCSTeamsAppPer
   missionPolicyCmdlet
    + PSComputerName        : admin0e.online.lync.com

**Comment by scanum** [comment] 2019-10-23 18:16
@Naz9mm  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Naz9mm** [comment] 2019-10-29 14:35
is there any update on this - I really don't want to have add users manually!

**Comment by get-itips** [comment] 2019-10-29 20:23
Hello @Naz9mm 
I could not reproduce your error, I see that you are passing EmailAddress and the error is saying that it is null value, did you check it currently holds a value? also is the EmailAddress the same value as the username in the tenant?

**Comment by get-itips** [comment] 2019-10-29 20:28
Nevermind, further test I could repro, will propose correcting the article changing $_.EmailAddress for $_.UserPrincipalName

**Comment by Naz9mm** [comment] 2019-10-30 08:59
Awesome – great that you could reproduce,  I will attempt to replace $.EmailAddress for $.UserPrincipalName and test again when I get a chance


Thanks

Naz Momoniat  ::  Infrastructure Technician
t. 01675 466 477  ::   [image] <https://twitter.com/thinkcrimson>   [LinkedIn] <https://www.linkedin.com/company/crimson>   [image] <https://www.youtube.com/thinkcrimson>   [Facebook] <https://www.facebook.com/crimsonuk/>    ::  www.crimson.co.uk

[image]<https://www.crimson.co.uk/>

**Comment by LanaChin** [comment] 2019-12-11 01:38
Thanks so much for your input @Naz9mm and @get-itips for the repro and corrections. The updates by @get-itips are merged.

**Closed by LanaChin** 2019-12-11 01:38 UTC
