### ISSUE TITLE
Assigning DR phone number via Teams Admin Center 

### ISSUE THREAD

**Issue by shtakeda** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8376] opened 2022-01-20 00:11 UTC
I saw this tweet posted by a Microsoft PM. Can you update the docs to add the guidance how to add DR phone numbers via TAC?
https://twitter.com/nomorephones/status/1481031286244327425?cxt=HHwWgoCq3fSG140pAAAA

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb2a9717-6565-8443-8833-f7fdce562781
* Version Independent ID: db88c4d6-5864-a481-86cf-465feb452d75
* Content: [Enable users for Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-enable-users)
* Content Source: [Teams/direct-routing-enable-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-enable-users.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by jlon125** [comment] 2022-01-24 19:17
I found this, but for me the Direct Routing dropdown and the phone number are still greyed out for existing users, and I can't make changes. Maybe its only for new users?

https://ucmart.uk/2022/01/13/assign-direct-routing-numbers-to-users-in-teams-admin-center/

**Comment by Reeced40** [comment] 2022-01-25 05:27
@shtakeda thank you for reaching out. Please have a look at this support article and let me know if it helps at all - https://techcommunity.microsoft.com/t5/microsoft-teams/unable-to-assign-user-number-to-a-user-in-ms-teams/m-p/2369932

**Comment by shtakeda** [comment] 2022-01-25 06:35
@Reeced40 , I mean that a new feature (assigning DR phone number) has been added. I'd like you to add the new guidance on doc; how to assign DR phone number via TAC.

**Comment by Reeced40** [comment] 2022-01-27 08:34
@shtakeda thank you for clearing this up. I'll have to find the official documentation confirming this and add it to the article. Thanks again for helping to improve Microsoft Docs.

**Comment by Reeced40** [comment] 2022-02-14 09:25
@shtakeda it looks like the article has been updated. Please have a look and let me know. Thanks again.

**Comment by CarolynRowe** [comment] 2022-02-14 23:10
Yes, the article was updated, but that was to update PowerShell info.  Working on the admin center content now.

**Comment by CarolynRowe** [comment] 2022-02-15 00:25
@Reeced40 I am working with the PMs on this issue now.  Please don't add any info to the content until you hear back from me.

**Comment by CarolynRowe** [comment] 2022-02-15 00:31
Latest update:  This feature has experienced regressions and the team continues to work on a remediation that will allow admin users to assign on-premises phone numbers to end-users.  As soon as the feature is fully functional, we will update the article.  Closing this issue for now.

**Closed by CarolynRowe** 2022-02-15 00:31 UTC
Labels: doc-bug
