### ISSUE TITLE
Partner application communication ports for office 365

### ISSUE THREAD

**Issue by hansarh** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#869] opened 2018-10-11 08:49 UTC
When setting up partner application and enabling OAuth for Office365, what ports needs to be open from Front End server to Echange online and Sharepoint online and microsoft sts? is port 443 as destination port enough? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5164207-7822-cf54-717e-6216e0627ebd
* Version Independent ID: 786f5413-3660-06eb-484f-8d5758d3ec59
* Content: [Port and protocol requirements for servers](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/network-requirements/ports-and-protocols)
* Content Source: [Skype/SfbServer/plan-your-deployment/network-requirements/ports-and-protocols.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/network-requirements/ports-and-protocols.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by AndreaBarr** [comment] 2018-10-16 20:21
@hansarh Thank you for this feedback

I want to make sure we get you the answers that you need. I am going to get this over to the Teams/Skype for Business team. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by jambirk** [comment] 2018-10-16 20:40
Andrea,

The article is specifically about on-premise implementations only. The office 365/ skype for business online implementation is a whole other ball of wax (which we already link to), and the hybrid implementation is described in the hybrid topics. For DNS, they need to whitelist appropriately for both on-prem and online.

I don’t agree that much if anything needs to be done here. Exchange OL integration is covered in its own topic, this is not the place to be doing it.


____________________________________________________________
James Birkinshaw     |    Skype for Business ITPro Content

**Comment by jambirk** [comment] 2018-10-16 20:56
I've added a link to the hybrid port and protocol discussion, alongside the existing link to online O365 implementations.

**Comment by AndreaBarr** [comment] 2018-10-16 22:01
@hansarh It looks like James has addressed your inquiry. I am going to close this issue. If the issue is not resolved please re-open this issue.

**Closed by AndreaBarr** 2018-10-16 22:01 UTC
