### ISSUE TITLE
Any way for admins to report issues while they customize apps?

### ISSUE THREAD

**Issue by prkosh** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9189] opened 2022-08-11 09:28 UTC
[Enter feedback here]
If the admin faces any blockers during app customization - can they reach out to us ? Is there any place to solicit questions from Admins that can be resolved ? If available - its good to point to those avenues here.

Also - there is mention of Testing on a Test Tenant - can you also point some documentation on how to create a test tenant for testing ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cb13dd7-3253-5406-0738-8c53ffc47752
* Version Independent ID: f843f426-6f77-691f-496a-e833efe7309e
* Content: [Modify the appearance of apps in your organization's Teams store - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/customize-apps)
* Content Source: [Teams/customize-apps.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/customize-apps.md)
* Service: **msteams**
* GitHub Login: @guptaashish
* Microsoft Alias: **guptaashish**

**Comment by ashishguptaiitb** [comment] 2022-08-12 21:16
That'd be the info to contact Microsoft official Support. 

Test tenant - a good overview article is at https://docs.microsoft.com/microsoftteams/platform/concepts/build-and-test/prepare-your-o365-tenant

**Comment by ashishguptaiitb** [comment] 2022-08-22 11:57
Option to provide feedback on the doc and for the products are available at the end of each help page. That's where folks can report suggestions. As for asking for Support while doing any config or while using Teams, the option to reach Microsoft's customer support is not mentioned explicitly on the each help page. I ought to check with the doc infra team.

**Comment by ashishguptaiitb** [comment] 2022-09-28 18:51
Point #1 is addressed by design. Our open-source docs allow for providing feedback.
As for seeking support, @SerdarSoysal mentioned that our customers are able to find support easily. via the link in the above comment.
Hence, I don't think we should mention adding support contact at an article level.

Closing this issue for now with this resolution. If not acceptable, please re-open.

**Closed by ashishguptaiitb** 2022-09-28 18:51 UTC
Labels: Microsoft submitter, doc-enhancement
