### ISSUE TITLE
The Org-wide setting is not available anymore.

### ISSUE THREAD

**Issue by kbog11** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8118] opened 2021-11-09 21:57 UTC
This section needs to be updated.
The Org-wide setting is not available anymore.

==================
Turn on scoped directory search
Use Information Barrier policies to configure your organization into virtual subgroups. For more information, see Define Information Barrier policies.

In the Microsoft Teams admin center, select Org-wide settings > Teams settings.
==============================

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c9b7f77-061d-a224-ff1c-8d3e15d21221
* Version Independent ID: 00fa9550-c4c4-3398-ffbb-271cc724048f
* Content: [Manage settings for your organization - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/enable-features-office-365)
* Content Source: [Teams/enable-features-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/enable-features-office-365.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment] 2021-11-10 13:33
Duplicate of https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7900

**Comment by get-itips** [comment] 2021-11-18 15:19
@scanum please close, the PR has been merged.

**Closed** 2021-11-23 16:52 UTC
Labels: doc-bug
