### ISSUE TITLE
Missing hyphen in cmdlet

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8779] opened 2022-04-20 18:39 UTC
"with the `SetOrganizationConfig` cmdlet"

should be

"with the `Set-OrganizationConfig` cmdlet"

(It's missing the hyphen).

I'm running into issue doing the pull request, so just sending the feedback instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5eb6a35-32fa-6703-8ed2-0855e602b7d5
* Version Independent ID: 7890ca09-d505-35a9-071a-8662a4b19275
* Content: [Use Microsoft 365 and custom connectors - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/office-365-custom-connectors)
* Content Source: [Teams/Office-365-custom-connectors.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Office-365-custom-connectors.md)
* Service: **msteams**
* GitHub Login: @guptaashish
* Microsoft Alias: **guptaashish**

**Comment by ashishguptaiitb** [comment] 2022-05-30 08:57
Closing this issue as resolved. The issue is corrected (via some other content update).

**Closed** 2022-05-30 08:58 UTC
Labels: Microsoft submitter, doc-bug
