### ISSUE TITLE
SQL Server 2016 missing

### ISSUE THREAD

**Issue by JohanVeldhuis** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#658] opened 2018-08-10 07:47 UTC
SQL server 2016 SP1 is supported when using CU7/July 2018:
https://support.microsoft.com/en-us/help/4100776/sql-server-2016-sp1-is-available-for-the-back-end-servers-of-skype

The following sections need to be updated:

Back end databases that will work with Skype for Business Server 2015
SQL Mirroring, SQL Clustering, and SQL Always On

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c475b5d-09ed-7f58-86d4-27f28e33ef7a
* Version Independent ID: f0ad50f3-ea93-9424-6de8-a0b778e90b23
* Content: [Server requirements for Skype for Business Server 2015](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/requirements-for-your-environment/server-requirements)
* Content Source: [Skype/SfbServer/plan-your-deployment/requirements-for-your-environment/server-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/requirements-for-your-environment/server-requirements.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by AndreaBarr** [comment] 2018-09-13 21:37
@JohanVeldhuis Thank you for this feedback

This is a duplicate of the below issue. I am closing this issue.

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/635

**Closed by AndreaBarr** 2018-09-13 21:37 UTC
Labels: Skype for Business Server
