### ISSUE TITLE
MSIX download link direct to wrong link

### ISSUE THREAD

**Issue by aliefamzari** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10532] opened 2023-10-30 01:23 UTC
MSIX download link incorrect. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4b73fb04-90e1-de2e-e81d-3495c004b2b5
* Version Independent ID: 4b73fb04-90e1-de2e-e81d-3495c004b2b5
* Content: [Bulk deploy the new Microsoft Teams desktop client - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/new-teams-bulk-install-client)
* Content Source: [Teams/new-teams-bulk-install-client.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/new-teams-bulk-install-client.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment] 2023-10-30 16:02
Hello @aliefamzari thanks for your feedback, I'm working on this

**Comment by get-itips** [comment] 2023-10-30 16:05
Duplicate of https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/10530

**Comment by get-itips** [comment] 2023-10-31 20:27
Fixed in https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/5e1aff2bd9bb8f4227b20c1f4dfb2ba6034823b9

**Closed by get-itips** 2023-10-31 20:27 UTC
Labels: doc-bug
