### ISSUE TITLE
Web page only provides x86 msix packages and not the ARM ones

### ISSUE THREAD

**Issue by LuisAmadeo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10540] opened 2023-10-31 12:06 UTC
[Enter feedback here]
The bulk installer section that indicates to download the bootstrap and the msix only has the x86 version to downlaod. The ARM version is not avaliable to download and it is needed to make an offline package

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4b73fb04-90e1-de2e-e81d-3495c004b2b5
* Version Independent ID: 4b73fb04-90e1-de2e-e81d-3495c004b2b5
* Content: [Bulk deploy the new Microsoft Teams desktop client - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/new-teams-bulk-install-client)
* Content Source: [Teams/new-teams-bulk-install-client.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/new-teams-bulk-install-client.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment] 2023-11-03 21:54
Duplicate of https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/10451

**Comment by JoanneHendrickson** [comment] 2023-11-03 21:58
Contacting the product team.

**Comment by JoanneHendrickson** [comment] 2023-11-29 21:37
@get-itips @LuisAmadeo   The articles have now been updated to include all 3 options listed -- x86, x64, & ARM 64.

**Closed by JoanneHendrickson** 2023-11-29 21:37 UTC
Labels: doc-bug
