### ISSUE TITLE
BToE IS currently supported on VDI platforms.

### ISSUE THREAD

**Issue by nicolasbroisin** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1062] opened 2018-11-14 11:45 UTC
Hello,
Regarding your note "BToE isn't currently supported on Mac and VDI platforms." I would like just to share to you that BTOE is supported on VDI :
On Audiocodes IP phones : https://blog.audiocodes.com/audiocodes-brings-you-skype-for-business-with-vdi
And on Polycom IP phones : https://community.polycom.com/t5/Skype-for-Business/Software-UC-Software-5-7-0/td-p/95737

I'm not sure about it is for Yealink ip phones .. 
I hope it helps to update this article.
Cheers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8473d3c9-66e3-0b24-e614-ddc454ea9554
* Version Independent ID: b14dcf01-eb59-cb18-013c-1bc2f33ca46a
* Content: [Deploying Skype for Business Online phones](https://docs.microsoft.com/en-us/skypeforbusiness/what-is-phone-system-in-office-365/getting-phones-for-skype-for-business-online/deploying-skype-for-business-online-phones)
* Content Source: [Skype/SfbOnline/what-is-phone-system-in-office-365/getting-phones-for-skype-for-business-online/deploying-skype-for-business-online-phones.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/what-is-phone-system-in-office-365/getting-phones-for-skype-for-business-online/deploying-skype-for-business-online-phones.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by MishaTravis** [comment] 2018-11-17 00:46
@nicolasbroisin  - Thank you for submitting this feedback.

I was able to get this into the backlog for the Skype team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by LolaJacobsen** [comment] 2018-11-19 21:45
@CarolynRowe - assigned to you

**Comment by kenwith** [comment] 2019-03-27 21:09
@scanum - I believe @LanaChin is working on this one and can coordinate with you. I believe PM has pushed back on associated PR so we will need to loop with the PM to find out how to resolve this issue. @LanaChin please coordinate with @scanum and @get-itips .

**Comment by LanaChin** [comment] 2019-03-29 15:47
@scanum, @get-itips - I reached out to the PM who confirmed that the current statement should not be changed. The links are partner implementations, not supported by Microsoft.

**Comment by scanum** [comment] 2019-03-29 16:23
@nicolasbroisin  Thank you for submitting this feedback.

From our understanding the issue has been resolved, since no changes should be made to statements. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment] 2019-03-29 16:23
@officedocsbot close

**Closed by scanum** 2019-03-29 16:23 UTC
