### ISSUE TITLE
SIGNINRESTRICTED blocks Teams 2.0 installation

### ISSUE THREAD

**Issue by albourne-dev** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9867] opened 2023-03-28 08:15 UTC
You are missing a case where although the toggle should appear it doesn't.
Both below values appear fine:

enggCompleteFlag: true, 
isAboveWin10Vibranium: true

But we are getting a 
code: SIGNINRESTRICTED, reason: Device is Sign-in restricted.

We need to figure out which policy applies and does this.

Tue Mar 28 2023 11:03:14 GMT+0300 (Eastern European Summer Time) <26516> -- event -- eventpdclevel: 1, code: SIGNINRESTRICTED, reason: Device is Sign-in restricted, policyValue: false, status: success, scenario: 7203ddf0-8d13-43e3-8d5e-ee23c448763d, scenarioName: appswitcher_appstateservice_check, name: appswitcher_appstateservice_check, step: unknown, sequence: 1, delta: 1, scenarioDelta: 1, elapsed: 291, stepDelta: 1, Scenario.Mode: 1, AppInfo.Language: en-us, complianceEnvironmentType: 0, isDataCategorizationEnabled: true, userpdclevel: 0, processMemory: 23955764, freeMemory: 3760246784, clientType: desktop, AppInfo.ClientType: desktop, Window.Focus: background, windowIsVisible: false, Window.Status: systray, UserInfo.TimeZone: +03:00, vdiMode: 0, previousVDIOptimizationValue: undefined, ppChannel: Production::MEC, distSrc: PROPLUS_O365ProPlusRetail,VisioProRetail,OneNoteFreeRetail, ppInstallMode: UPDATE, autoStartPolicy: 1, Scenario.Name: appswitcher_appstateservice_check, Scenario.Step: unknown, Scenario.Status: success,  
Tue Mar 28 2023 11:03:14 GMT+0300 (Eastern European Summer Time) <26516> -- event -- eventpdclevel: 1, code: PEAR_APP_DISABLED, enggCompleteFlag: true, isAboveWin10Vibranium: true, policyCode: SIGNINRESTRICTED, returnValue: undefined, status: abandoned, scenario: 7203ddf0-8d13-43e3-8d5e-ee23c448763d, scenarioName: appswitcher_appstateservice_check, name: appswitcher_appstateservice_check, step: stop, sequence: 2, delta: 1, scenarioDelta: 1, elapsed: 291, stepDelta: 0, Scenario.Mode: 1, AppInfo.Language: en-us, complianceEnvironmentType: 0, isDataCategorizationEnabled: true, userpdclevel: 0, processMemory: 24001444, freeMemory: 3760246784, clientType: desktop, AppInfo.ClientType: desktop, Window.Focus: background, windowIsVisible: false, Window.Status: systray, UserInfo.TimeZone: +03:00, vdiMode: 0, previousVDIOptimizationValue: undefined, ppChannel: Production::MEC, distSrc: PROPLUS_O365ProPlusRetail,VisioProRetail,OneNoteFreeRetail, ppInstallMode: UPDATE, autoStartPolicy: 1, Scenario.Name: appswitcher_appstateservice_check, Scenario.Step: stop, Scenario.Status: abandoned, 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d50c2e0-d6d3-ec3f-5e99-acaa2a6868d5
* Version Independent ID: 1d50c2e0-d6d3-ec3f-5e99-acaa2a6868d5
* Content: [The new Microsoft Teams desktop client - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/new-teams-desktop-admin?tabs=teams-admin-center)
* Content Source: [Teams/new-teams-desktop-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/new-teams-desktop-admin.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by albourne-dev** [comment] 2023-03-28 08:29
I found the root cause. Please update the document accordingly.

Tue Mar 28 2023 11:26:42 GMT+0300 (Eastern European Summer Time) <42452> -- event -- eventpdclevel: 1, code:
PEAR_APP_ENABLED, enggCompleteFlag: true, isAboveWin10Vibranium: true, policyCode: NON_BLOCKING, returnValue: true,
status: success, scenario: e6481b9a-4b9b-4209-96f9-da5eb00556b5, scenarioName: appswitcher_appstateservice_check, name:
appswitcher_appstateservice_check, step: stop, sequence: 2, delta: 1, scenarioDelta: 1, elapsed: 113, stepDelta: 0,
Scenario.Mode: 1, AppInfo.Language: en-US, complianceEnvironmentType: 0, isDataCategorizationEnabled: true, userpdclevel:
0, processMemory: 27654132, freeMemory: 3198304256, clientType: desktop, AppInfo.ClientType: desktop, UserInfo.TimeZone:
+03:00, vdiMode: 0, previousVDIOptimizationValue: undefined, ppChannel: Production::MEC, distSrc:
PROPLUS_O365ProPlusRetail,VisioProRetail,OneNoteFreeRetail, ppInstallMode: UPDATE, autoStartPolicy: undefined,
Scenario.Name: appswitcher_appstateservice_check, Scenario.Step: stop, Scenario.Status: success,

We are using a Group Policy as per below:
**Restrict sign in to Teams to accounts in specific tenants**

https://admx.help/?Category=Office2016&Policy=Teams.Office.Microsoft.Policies.Windows::String_Teams_SignInRestriction_Policy

This blocks the upgrade. Is it by design or should it obey this setting?
I believe it should work even with this GPO in place.

**Comment by wmadm90** [comment] 2023-03-28 17:00
I'm also seeing the same. It would be good to know if this is by design or not intended/will be fixed. Thanks!

**Comment by nzdudeinsydney** [comment] 2023-03-29 03:49
I'm seeing the same. Here's my entries from logs.txt:

Wed Mar 29 2023 14:38:03 GMT+1100 (Australian Eastern Daylight Time) <13132> -- event -- eventpdclevel: 1, code: PEAR_APP_DISABLED, enggCompleteFlag: true, isAboveWin10Vibranium: true, policyCode: SIGNINRESTRICTED, returnValue: undefined, status: abandoned, scenario: [GUID REMOVED BY AUTHOR], scenarioName: appswitcher_appstateservice_check, name: appswitcher_appstateservice_check, step: stop, sequence: 2, delta: 1, scenarioDelta: 1, elapsed: 392, stepDelta: 0, Scenario.Mode: 1, AppInfo.Language: en-us, complianceEnvironmentType: 0, isDataCategorizationEnabled: true, userpdclevel: 1, processMemory: 23572004, freeMemory: 8165888000, clientType: desktop, AppInfo.ClientType: desktop, Window.Focus: background, windowIsVisible: false, Window.Status: systray, UserInfo.TimeZone: +11:00, vdiMode: 0, previousVDIOptimizationValue: undefined, Scenario.Name: appswitcher_appstateservice_check, Scenario.Step: stop, Scenario.Status: abandoned,

**Comment by SmuSmu** [comment] 2023-03-30 11:57
It is the Policy restrictteamssignintoaccountsfromtenantlist.

The restriction to Teams to only allow a specific mandant

**Comment by Vima143** [comment] 2023-04-13 15:46
Confirming that root cause is the Policy restrictteamssignintoaccountsfromtenantlis which classifies the users as sign-in restricted users. Microsoft confirmed rollout excludes: EDU, VDI, Special Clouds, Mac, Web, Consumer, unsupported OS, and users with sign-in restrictions. Estimated time for sign-in enabled users is late May 2023. 

More on the RestrictTeamsSignInToAccountsFromTenantList policy: https://learn.microsoft.com/en-us/microsoftteams/sign-in-teams#how-to-restrict-teams-sign-in-on-desktop-devices

**Comment by JoanneHendrickson** [comment] 2023-05-11 14:56
This is addressed here: https://learn.microsoft.com/en-us/microsoftteams/new-teams-desktop-admin?tabs=teams-admin-center#policies-that-could-block-the-user-from-seeing-the-app-switcher-toggle 

**Policies that could block the user from seeing the App switcher toggle**
The following list of policies can block users from seeing the app switcher toggle.


- Your admin has sign in restrictions set up [Learn more about how to restrict Teams sign in on desktop devices](https://learn.microsoft.com/en-us/microsoftteams/sign-in-teams#how-to-restrict-teams-sign-in-on-desktop-devices)
- If the user is on a VDI computer (Citrix, VMware etc.).
- If the user is signed in to classic Teams with a Teams for Life account and a work account.
- If the user is signed in to classic Teams with a Teams for Life account.
- If you have an MSIX client.

**Closed by JoanneHendrickson** 2023-05-11 14:56 UTC
Labels: doc-bug
