### ISSUE TITLE
additional blocking setting is missing

### ISSUE THREAD

**Issue by SmuSmu** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9884] opened 2023-03-30 11:55 UTC
GPO Policy "restrictteamssignintoaccountsfromtenantlist" is also blocking the Toggle Button.

Please add some info to this aswell

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d50c2e0-d6d3-ec3f-5e99-acaa2a6868d5
* Version Independent ID: 1d50c2e0-d6d3-ec3f-5e99-acaa2a6868d5
* Content: [The new Microsoft Teams desktop client - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/new-teams-desktop-admin?tabs=teams-admin-center)
* Content Source: [Teams/new-teams-desktop-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/new-teams-desktop-admin.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by SmuSmu** [comment] 2023-03-30 11:58
This Policy here https://admx.help/?Category=Office2016&Policy=Teams.Office.Microsoft.Policies.Windows::String_Teams_SignInRestriction_Policy&Language=en-us

**Comment by SmuSmu** [comment] 2023-04-04 07:31
Hi,

I say that If this value ist setted by an gpo the toggle will Not Show Up. All other settings mentioned in the Docs are setted correctly. The Moment i removed that specific gpo setting the toggle showed Up. After Gpupdate / Teams restart of course.

I also saw some Checks in the Log about that. So I guess Something is Missing in the Docs.

**Comment by dariomws** [comment] 2023-04-04 07:37
Thanks @SmuSmu for your help.

I found that this information is included in the article:
https://learn.microsoft.com/microsoftteams/new-teams-desktop-admin#policies-that-could-block-the-user-from-seeing-the-app-switcher-toggle

#### Policies that could block the user from seeing the App switcher toggle

The following list of policies can block users from seeing the app switcher toggle.

- If the user is on a VDI computer (Citrix, VMware etc.). 
- If the user is signed in to classic Teams with a *Teams for Life* account and a work account. 
- If the user is signed in to classic Teams with a *Teams for Life* account.
- If you have an MSIX client. 
- [Learn more about how to restrict Teams sign in on desktop devices](https://learn.microsoft.com/microsoftteams/sign-in-teams#how-to-restrict-teams-sign-in-on-desktop-devices)

**Comment by mosslive** [comment] 2023-04-04 15:02
The documentation is correct, when mentioning this, however, the table in the paragraph below "How do I know which one of the above policies is blocking me?" -> at "6. Check the code to find out the cause." doesn't mention the according code "SIGNINRESTRICTED" that can be found in the log.txt for this case.
Would help people to identify the cause, if this would be added to the table.

**Comment by tiburd** [comment] 2023-09-28 22:45
Documentation team confirmed that this is being addressed in the private repo.

**Closed by tiburd** 2023-09-28 22:45 UTC
Labels: doc-bug
