### ISSUE TITLE
Showing "![Screenshot showing banner notification guest users](media/guest-experience-image2.png"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2349] opened 2019-05-30 16:32 UTC
https://docs.microsoft.com/en-us/microsoftteams/guest-experience

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 048930a4-fdf2-9a90-3b47-46af66db3db4
* Version Independent ID: 8d6a2c84-94e9-b17e-f5c1-91191187ce4e
* Content: [What the guest experience is like](https://docs.microsoft.com/en-us/microsoftteams/guest-experience)
* Content Source: [Teams/guest-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-experience.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment] 2019-05-30 18:54
@hyoshioka0128 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by hyoshioka0128** [comment] 2019-05-31 03:51
en-us:https://docs.microsoft.com/en-us/microsoftteams/guest-experience
![guest-experience_e](https://user-images.githubusercontent.com/40815708/58680434-ace2dc00-83a2-11e9-8fba-fe3f8c8d0d9d.png)

ja-jp:https://docs.microsoft.com/ja-jp/microsoftteams/guest-experience
![guest-experience_j](https://user-images.githubusercontent.com/40815708/58680458-c4ba6000-83a2-11e9-83bd-2d9d2fb99348.png)

**Comment by sowjanya365** [comment] 2019-06-11 18:11
Hi @hyoshioka0128 

Thank you for reaching out! We appreciate your time!!

Yes, these banner notifications on the screenshot to highlight the text related to guest addition to the room. Kindly help us to understand if you find something wrong with the notifications.

Please correct me if my understanding about the issue is wrong. Looking forward to your response. Thank you.

**Comment by hyoshioka0128** [comment] 2019-06-12 10:26
@sowjanya365 : Thank you. (I'm poor English.)
I thought at that time that the code was being displayed without the "media/guest-experience-image2.png" image being displayed.
Now that the code is not displayed and fixed, please close it.

en-us:https://docs.microsoft.com/en-us/microsoftteams/guest-experience
![guest-experience_e](https://user-images.githubusercontent.com/40815708/59343857-b9bee280-8d47-11e9-8fdd-e327e63f32f4.png)

ja-jp:https://docs.microsoft.com/ja-jp/microsoftteams/guest-experience
![guest-experience_j](https://user-images.githubusercontent.com/40815708/59343867-bfb4c380-8d47-11e9-90db-711668e305f3.png)

**Comment by sowjanya365** [comment] 2019-06-12 16:58
Hi @scanum 

Kindly close this issue. Thank you.

**Comment by scanum** [comment] 2019-06-21 16:23
@hyoshioka0128 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment] 2019-06-21 16:23
@officedocsbot close

**Closed by scanum** 2019-06-21 16:23 UTC
