### ISSUE TITLE
Confusing tip

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1398] opened 2019-01-15 16:37 UTC
In the "tip" near the top of this page, it says "You might have noticed that we no longer call out specific versions of the drivers, Skype Room Systems v2 client, or Windows 10 Enterprise. This is deliberate".
I find this really confusing. As a VLSC customer, I am able to download 1709, 1803 or 1809. However, from previous experience, the SRS app isn't always supported on the latest versions. I can't see on here what version of the app comes down with the script or what versions of WIn10 it will work with. 
I'm going to take my luck with 1809 but it could be wasting my time if SRS doesn't work on that yet

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51d42140-9f7b-a6f3-7a3e-76cc7331cf22
* Version Independent ID: a7dacc56-c2df-55fb-76a3-ecb194564fae
* Content: [Configure a Skype Room Systems v2 console](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/console#Prep_Media)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/console.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment] 2019-01-15 17:18
Not calling out specific versions is indeed deliberate, because the intention is that you rely on the media creation script which should fetch the drivers etc for you. This is precisely because there are so often support lags and SRS may or may not work with the most recently released versions of driver or OS, but the script _is_ updated when we verify new versions to be compatible with SRS. Let the script handle that for you.

**Comment by thommck** [comment] 2019-01-15 17:37
I understand that but the script doesn't download the Win 10 ISO for us.
(as a side note, it would be useful to show an image of the script output or a small video of it running so users know what to expect)

Only by running it, and confirming you already have the WIn10 media available, does it tell you the following information:
		"Validating signature for SRSDeploymentKit-4.0.64.1.msi... success.
		Extracting the deployment kit... done.
		This deployment kit is built for Windows build 10.0.17134.1."
I know have to go on to Wikipedia to check that 17134 actually means 1803. Only at that point will I be ready to download the ISO from the VLSC.

If the script told me that info at the start then I would be able to be fully prepared. In my case, I know haven't been able to complete this task today which means I will no be delayed in getting our meeting room back up and running

**Comment by Travis-Snoozy** [comment] 2019-01-15 18:19
> the script doesn't download the Win 10 ISO for us

ISOs for Enterprise are not publicly available. Because of this, the script cannot download the ISOs on your behalf.

> Only by running it, and confirming you already have the WIn10 media available, does it tell you the following information:

This statement is not wholly accurate. While the instructions to the operator are to "make sure you have all of the following available," with the list including "Windows 10 Enterprise IoT media that matches your SRSv2 deployment kit," Windows 10 media is **not** required up-front for the script to emit its Windows version requirement information. This is by design. The path to the Windows 10 media is not requested until much later in the script's execution, well after the information is available on exactly what build is necessary -- it is entirely possible to run the script, leave it running at that prompt (or any prompt prior), download appropriate media, and then return to the script.

> If the script told me that info at the start then I would be able to be fully prepared.

The script indicates the version as soon as it can. However, to know what version is needed, the script must download the latest deployment kit, and decompress it. That currently-published kit is what determines what exact build of Windows is required. The script takes care of downloading and performing that check automatically.

**Comment by Travis-Snoozy** [comment] 2019-01-15 18:30
I concur that the "Tip" is misleading.



> Tip

> You might have noticed that we no longer call out specific versions of the drivers, Skype Room Systems v2 client, or Windows 10 Enterprise. This is deliberate, we want the script to match and verify compatibility for all installers. The script will automatically find and get what it needs for a supported configuration.

The script absolutely does not and can not download the Windows 10 Enterprise ISO. I would strongly recommend simply deleting this "tip."

**Comment by Travis-Snoozy** [comment] 2019-01-15 18:33
... furthermore, the "Note" earlier on the page explicitly calls out a version. I would recommend deleting that as well.



> Note

> Failure to create your Skype Room Systems v2 installation media according to these instructions will likely result in unexpected behavior. ~Windows 10 Enterprise Anniversary Update (Version 1607) is no longer supported for Skype Room Systems v2 installation media creation.~

**Comment by jambirk** [comment] 2019-01-15 18:43
I'll update this page later today.

**Comment by thommck** [comment] 2019-01-15 18:44
Deleting the tip is an option. I think when a person comes to this page they want to know what version of the app/windows is going to be installed, so it would be better to say something like: "after you download and run the Script you will be informed what version of the provisioning kit will be used and what version of Windows you'll need to download yourself"
________________________________

**Comment by Travis-Snoozy** [comment] 2019-01-15 23:16
PR #1402

**Comment by jambirk** [comment] 2019-01-17 18:20
Closing this issue now, please re-open if there's more needed.

**Closed by jambirk** 2019-01-17 18:20 UTC
