### ISSUE TITLE
Unable to see end-user features

### ISSUE THREAD

**Issue by FunkyCat123** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9926] opened 2023-04-11 17:34 UTC
After following all the steps including the policy assignment and enabling public preview in the client, there is nothing new for the end-user to manage auto attendant or call queue.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bdc17ac9-a82b-8705-fc77-5d0ecdcb2b56
* Version Independent ID: bdc17ac9-a82b-8705-fc77-5d0ecdcb2b56
* Content: [Set up auto attendant and call queue authorized users - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/aa-cq-authorized-users)
* Content Source: [Teams/aa-cq-authorized-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/aa-cq-authorized-users.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by CLYVR** [comment] 2023-04-11 19:59
@FunkyCat123 Please confirm that in addition to creating the policy and enabling for public preview that you have also assigned the users as "authorized users" to at least one auto attendant or call queue.  Also, please ensure the end-user(s) have the latest version of the Teams Client.

**Comment by FunkyCat123** [comment] 2023-04-11 20:15
Correct. I followed the article step by step. Account has been assigned to authorized users and client is running latest version of Teams client. I also tried the new Teams version but that made no difference. I am assuming the management option will appear in Settings - Voice. But I looked everywhere else as well.

**Comment by CLYVR** [comment] 2023-04-11 20:40
Hi @FunkyCat123 The options should appear under Settings -> Calls.  There should be a title "Call queue or auto attendant" and the Auto Attendants/Call Queues the user is a member of and also authorized for should appear there.

![Client](https://user-images.githubusercontent.com/67927199/231282567-8a77b29f-9add-407f-827c-fc0c0d95da5d.png)

**Comment by FunkyCat123** [comment] 2023-04-11 21:04
Thanks Colin. That's what I assumed it should look like and yes. It's not there. I only see call queues that account is a member of. My client version is 1.6.00.9372 which I believe is the latest. Any-thing else I should be trying?

**Comment by CLYVR** [comment] 2023-04-12 01:30
@FunkyCat123 No, based on our conversation it sounds like you've done everything correctly.  I know sometimes it takes some time for these changes to propogate through the system but if you're still experiencing the problem then please open a ticket with support.

**Comment by CLYVR** [comment] 2023-04-17 04:33
Hi @FunkyCat123.  I wanted to follow up on this to see if the problem is resolved/the settings appeared or if there was something wrong.  Did you have to open a ticket/ICM on this and if so, would you give me the number so I can go look it up?  Thanks!.

**Comment by scanum** [comment] 2023-07-03 05:45
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Closed by scanum** 2023-07-03 05:45 UTC
Labels: product-feedback
