### ISSUE TITLE
Phone system license not a requirement for voicemail provisioning

### ISSUE THREAD

**Issue by TheBluLion** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7727] opened 2021-08-20 20:08 UTC
Phone system license is not a requirement for cloud voicemail functionality as noted in announcement in 2019
https://tomtalks.blog/2019/04/voicemail-is-now-on-by-default-for-all-voip-enabled-users-in-microsoft-teams/#:~:text=Microsoft%20Teams%20has%20VoIP%20calling%20by%20default%2C%20both,in%20their%20calls%20app%20in%20the%20app%20bar.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8228f9b2-a7de-abb4-6f41-70db0b3af155
* Version Independent ID: 8fd9fafb-dd76-59a8-e609-56f06d539a31
* Content: [Set up Cloud Voicemail - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-phone-system-voicemail)
* Content Source: [Teams/set-up-phone-system-voicemail.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-phone-system-voicemail.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment] 2021-08-23 19:46
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment] 2021-08-23 22:44
Duplicate of https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7603

**Closed** 2021-09-03 03:14 UTC
Labels: doc-bug
