### ISSUE TITLE
1:1 Inter polarity with SFB and Teams

### ISSUE THREAD

**Issue by moore1emu** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#187] opened 2018-05-15 16:08 UTC
We have noticed that SFB to Teams communications only works as long as one of the Users only has SFB.

If Both Users have Teams account, but is signed out of one, interpolarity no longer works.

Example:

Works: 

- User A on **SFB**, **No Teams Account**. , is able to message User B on **Teams**.

Does Not Work: 

Once User A has a Teams account, this no longer works. 

-  User A on **SFB**, with **Teams Closed**, is no longer able to message User B on **Teams**, with **SFB closed**. (emails get sent to inbox)

-  User A on **Teams**, with **SFB Closed**, is no longer able to message User B on **SFB**, with **Teams Closed** (email is sent to inbox)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41ddf8ce-fda9-ee9d-d96a-801f9a2f66b7
* Version Independent ID: 9aa5a49f-c440-95a8-83a1-9d38bdaeda39
* Content: [Known issues for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/known-issues)
* Content Source: [Teams/Known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Known-issues.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by kenwith** [comment] 2018-05-16 19:38
@moore1emu - Looking into this to see how I can make the documentation better. Thank you for reporting!

**Comment by kenwith** [comment] 2018-05-31 19:47
@moore1emu - I created this Pull Request (PR) and am just getting sign off from the product team to make sure there isn't a configuration that we are missing that might help solve this. Let me know if it accurately reflects the issue. The PR is #293

**Comment by kenwith** [comment] 2018-06-07 16:05
hi @moore1emu - I found out that this is a by design since after a person is upgraded to Teams the communications go to Teams and closing teams would cause a problem for message flow. We will look for places to make this clearer in the docs but isn't really a bug that can be included in the known-issues list. Thanks for feedback on this and I will try to make it clearer.

**Closed by kenwith** 2018-06-07 16:05 UTC
Labels: Microsoft Teams, Skype for Business Online, Skype for Business Server
