### ISSUE TITLE
Broken link "https://portal.azure.com"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2028] opened 2019-04-12 08:44 UTC
After #1788, Broken link  "1. [https://portal.azure.com] にサインインします。"

https://docs.microsoft.com/ja-jp/microsoftteams/guest-access-checklist

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: f737e278-7c89-e048-b60b-287615a829fb
* Version Independent ID: 1df35258-7360-74c4-680a-e154c54291fe
* Content: [Microsoft Teams のゲスト アクセスのチェックリスト](https://docs.microsoft.com/ja-jp/microsoftteams/guest-access-checklist)
* Content Source: [Teams/guest-access-checklist.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access-checklist.md)
* Service: **msteams**
* GitHub Login: @somakbhattacharyya
* Microsoft Alias: **sbhatta**

**Comment by scanum** [comment] 2019-04-15 19:42
@officedocsbot assign @scanum

**Comment by Jcoetsee** [comment] 2019-04-23 12:55
@somakbhattacharyya Can you check this item please, I checked the content source and the link appears to be functional so I am not sure what the issue is here.

**Comment by LolaJacobsen** [comment] 2019-05-07 18:22
I merged the PR fixing the link.

**Closed by LolaJacobsen** 2019-05-07 18:22 UTC
