### ISSUE TITLE
Screenshot is not available

### ISSUE THREAD

**Issue by ChristianSchn** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1918] opened 2019-03-29 16:07 UTC
Please reactivate the screenshot. I am not an admin but need to know what kind of metrics this report has to offer. Thanks.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 5b138331-2f10-a05d-7e88-68e62e0b3e4f
* Version Independent ID: f923b648-ffe4-8a8a-c189-6e31f1032c10
* Content: [Microsoft Teams – Nutzungsbericht](https://docs.microsoft.com/de-de/microsoftteams/teams-analytics-and-reports/teams-usage-report#feedback)
* Content Source: [Teams/teams-analytics-and-reports/teams-usage-report.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-analytics-and-reports/teams-usage-report.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment] 2019-03-29 16:15
@officedocs assign @scanum

**Comment by lindspea** [comment] 2019-04-16 14:26
@Office Global

**Comment by OfficeGlobal** [comment] 2019-04-18 13:16
Working on a fix

**Comment by OfficeGlobal** [comment] 2019-04-23 13:04
@ChristianSchn , @scanum article has been HumanTranslated and published live. The issue is fixed

**Comment by scanum** [comment] 2019-04-24 04:28
@ChristianSchn  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment] 2019-04-24 04:29
@officedocsbot close

**Closed by scanum** 2019-04-24 04:29 UTC
