### ISSUE TITLE
Issue: Guest users are able to share their screen but unable to give control

### ISSUE THREAD

**Issue by USAFin0365** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3285] opened 2019-10-28 14:05 UTC
Please list this as an issue. There are frustrated users, clients, and support personnel who need this feature ASAP. I have seen various forum posts stating that the Microsoft Teams Product Development team is aware of the issue. If they are aware of the issue, why isn't it listed here.

Please reference the comment from Nemanja Pantelic - Microsoft Agent | Moderator on 10/03/19 on this answers.microsoft.com forum - https://answers.microsoft.com/en-us/msoffice/forum/all/cant-give-control-of-screen-when-sharing-it-with/47d290b9-dcca-484d-9d54-4f713da9e211

Please list this issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41ddf8ce-fda9-ee9d-d96a-801f9a2f66b7
* Version Independent ID: 9aa5a49f-c440-95a8-83a1-9d38bdaeda39
* Content: [Known issues for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/known-issues#feedback)
* Content Source: [Teams/Known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Known-issues.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment] 2019-10-28 18:16
@USAFin0365  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by VLG17** [comment] 2020-01-09 13:02
@USAFin0365 Are you still seeing this as an issue? According to the comment from Nemanja Pantelic posted on November 22 in the thread you mentioned, it should have been fixed by now.

"The fix for the issue is in late testing phase. It has been implemented to the last Microsoft ring of users which usually means we can expect it rolled out to all end-users in next few weeks. "

**Comment by scanum** [comment] 2020-01-13 04:51
@USAFin0365 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Closed by scanum** 2020-01-13 04:51 UTC
