### ISSUE TITLE
Unable to obtain Windows 10 Enterprise version 10.0.18362.356

### ISSUE THREAD

**Issue by Matthew-Lyle** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4181] opened 2020-03-17 15:36 UTC
Hi, we are unable to obtain Windows 10 Enterprise version 10.0.18362.356 from our VLSC account.  instead we can only get the latest i.e. 10.0.18362.720.
Could you please update the  CreateSrsMedia.ps1 script to use this latest version, or help us in obtaining the previous version of Windows 10.

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f8b204f-9650-d268-8566-7a75ba0a1b6a
* Version Independent ID: 9a963e63-6716-7522-8abe-c8a407d3a46d
* Content: [Configure a Microsoft Teams Rooms console - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/console#feedback)
* Content Source: [Teams/rooms/console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/console.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by Matthew-Lyle** [comment] 2020-03-17 15:37
*didnt clarify, the script specifically wants version 10.0.18362.356 and wont accept older or newer versions that we have to hand.

**Comment by scanum** [comment] 2020-03-18 07:23
@Matthew-Lyle Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by iamalexmang** [comment] 2020-03-19 22:38
I too am facing the same blocker.

**Comment by iamalexmang** [comment] 2020-03-20 01:35
I want to additionally clarify the problem: the request for 10.0.18362.356 seems to be unrealistic. Business editions for Windows 10 Enterprise 1909 were available in October, December, January and February. The specific version for each of these are 10.0.18362.418, 10.0.18362.535, 10.0.18362.592 and 10.0.18362.720 specifically.

**Comment by iamalexmang** [comment] 2020-03-24 09:26
@scanum, do you or anyone else on the team happen to have an update on this matter?

**Comment by scanum** [comment] 2020-03-26 06:31
@iamalexmang We are working on this. Thanks!

**Comment by scanum** [comment] 2020-03-26 06:31
@Reeced40

**Comment by Reeced40** [comment] 2020-04-02 13:11
@Matthew-Lyle Thank you for reaching out to improve MS Docs. @richeklund has had the same issue in the past and here is what he came up with: 
I have a profile.ps1 in my WindowsPowerShell directory in my documents folder. I didn't use it anymore, but had a "Write-Host" line in there, which I didn't comment out from when I did.

I was able to replicate it by deleting the contents of profile.ps1 and putting write-host "Test" in the file. Launching powershell then gives the error. If I delete, or delete the contents of profile.ps1 so there is no write-host entries, it works fine. Write-Output also gives the error when launching this script. I tried a few other commands, such as changing directories, and it worked fine, but write-host or write-output in the profile.ps1 broke the script. 
Please let me know if this doesn't answer your question.

**Comment by iamalexmang** [comment] 2020-04-02 15:38
@Reeced40, are you sure you replied to the right thread? I've elaborated the error and the test with various versions of Windows, and what you've replied doesn't seem related in any way. I'm wondering what I might be missing.

**Comment by Reeced40** [comment] 2020-04-06 08:09
@iamalexmang Apologies. It looks like I replied to the incorrect thread, I will investigate further.

**Comment by Reeced40** [comment] 2020-04-07 08:03
@LanaChin Could you possibly assist please?

**Comment by LanaChin** [comment] 2020-04-08 15:42
Followed up with PM.

**Comment by iamalexmang** [comment] 2020-04-09 10:59
@LanaChin, by PM are you referring to Program Manager or a Private Message which I'm not seeing anywhere?

**Comment by LanaChin** [comment] 2020-04-10 17:06
Hi @iamalexmang - I'm referring to the Program Manager. :-)

**Comment by JeroenDijkman** [comment] 2020-04-20 13:37
@LanaChin  @scanum  Any update on this issue? We are facing the same problem.
Any feedback is highly appreciated.

**Comment by Pawel7471** [comment] 2020-04-24 14:25
Same problem here, any update?

**Comment by LanaChin** [comment] 2020-04-24 14:34
Over to you @dstrome.

**Comment by LanaChin** [comment] 2020-04-24 14:42
Reassigning to @dstrome.

**Comment by rquezada94** [comment] 2020-04-28 23:17
Was there a fix for this issue? I really need it also.

**Comment by JeroenDijkman** [comment] 2020-04-30 08:32
Hi All,

Besides this automation script is there also a way to perform a manual installation for the Teams Rooms device?

**Comment by scanum** [comment] 2020-05-06 03:50
@dstrome Hi David, any updates here? Thanks!

**Comment by dstrome** [comment] 2020-05-11 17:57
hi all,

I've pinged the product team to determine whether this process is still supported.

**Comment by supersankary** [comment] 2020-05-20 13:35
Hey, i had the same problem.
To solve this on your own is a bit tricky but it worked for me.

Download Media Creation tool1903, you can still find it in the web.
Start an elevated console and navigate to the folder where you file is located.

MediaCreationTool1903.exe /Eula Accept /Retail /MediaLangCode de-DE /MediaArch x64 /MediaEdition Enterprise

!!Change the language in the code above for your version, mine is de-DE for German language
Here is a list: https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/available-language-packs-for-windows

The tool will ask you for a key, choose you version and key from following page
https://docs.microsoft.com/sl-si/windows-server/get-started/kmsclientkeys
You can activate it later with your own key when the installation of the TRS is done.

Now you have a Windows 10 Enterprise 1903 - 18362... but still the wrong version, i had 10.0.18362.592 atleast you have Enterpise 10 1903 which is not LTSC or LTSB, which I coudnt find anywehere.

Next Step is to edit your iso to the needed version.
Unpack your iso file -> locate the install.esd in the sources folder and delete it.
Download an Enterprise 1903.18362.356 esd file, you can find this also in the web.
Check with dism.exe which versions are included in your esd file: enter the location where your file is located.
dism.exe /Get-WimInfo /WimFile:C:\Temp\Windows10_1903\sources\install.esd

You will receive an index list with Win 10 Pro, Enterprise, Enterprise and more.
Choose your index Windows 10 Enterprise: Mine was Index 3

Now create a SKU install.wim from the source install.esd with your index verion.

dism.exe /Export-Image /SourceImageFile:C:\Temp\Windows10_1903\sources\install.esd /SourceIndex:3 /DestinationImageFile:C:\Temp\Windows10_1903\sources\install.wim /Compress:max /CheckIntegrity

Copy the created install.wim into your unpacked iso where you have deleted the esd file earlier. Imagefolder\sources\

Now you have to make an new ISO from the unpacked folder, take the whole Image folder, not only sources.
Not sure if Windows 10 can do this, but you can find freeware for this in the web.

Mount the ISO, choose the right drive letter in the SRS script and it should work.


NOW: I have another problem aswell:
After installing the Teams room system as it should. All the Teams konfiguration done, Firmware is up to date ....
The Skype user is logged in but the Team Room App will not start automatically.
I can click the Start Button- and click on the Teams App which is pinned to Startmenu.
I have tested hours and hours with autostart, registry, but I am not able to get this app running automaticalle.
System version is the newest 4.4.41 and windows enterprise 10 1903
I was running Windows 17134 and an old Teams Room System before. There was connectivity problems between Skype and Teams, but atleast the app was running and autostarting as it should.
And I think it is not normal that the Skype user can use the start menu right?
The system in one of our other locations made an automatic update to version 4.4.41 and they have the same problem.

**Comment by Pawel7471** [comment] 2020-05-21 09:57
I downloaded Windows 10, version 1903 (updated Sept 2019) 64-bit Polish version from VLSC today, run it witch CreateSrsMedia.ps1 script (Polycom MSR  + Surface Pro (2017)), and...

Using SRSv2 kit:       C:\Users\pmaczka\Desktop\TEAMS\SRSDeploymentKit-4.4.41.0.msi
Using driver packs:
    C:\Users\pmaczka\Desktop\TEAMS\SurfacePro_Win10_16299_1806007_3.msi
Using Windows media:   f:
Using language packs:
Using updates:
Writing stick:         ADATA USB Flash Drive

Formatting and partitioning the target drive... done.
Copying Windows... done.
Copying the installation image... done.
Splitting the installation image... done.
Injecting drivers... done.
Copying Rigel build... done.
Configuring unattend files... done.
Selecting image... done.
Cleaning up... done.

Please safely eject your USB stick before removing it.

Everything is working !

**Comment by supersankary** [comment] 2020-05-25 05:05
> 
> 
> I downloaded Windows 10, version 1903 (updated Sept 2019) 64-bit Polish version from VLSC today, run it witch CreateSrsMedia.ps1 script (Polycom MSR + Surface Pro (2017)), and...
> 
> Using SRSv2 kit: C:\Users\pmaczka\Desktop\TEAMS\SRSDeploymentKit-4.4.41.0.msi
> Using driver packs:
> C:\Users\pmaczka\Desktop\TEAMS\SurfacePro_Win10_16299_1806007_3.msi
> Using Windows media: f:
> Using language packs:
> Using updates:
> Writing stick: ADATA USB Flash Drive
> 
> Formatting and partitioning the target drive... done.
> Copying Windows... done.
> Copying the installation image... done.
> Splitting the installation image... done.
> Injecting drivers... done.
> Copying Rigel build... done.
> Configuring unattend files... done.
> Selecting image... done.
> Cleaning up... done.
> 
> Please safely eject your USB stick before removing it.
> 
> Everything is working !

Normal Windows 10v1903 or Enterprise Version?

**Comment by Reeced40** [comment] 2020-06-03 14:00
@Matthew-Lyle Please let me know if the issue is resolved from your side as suggested above.

**Comment by iamalexmang** [comment] 2020-06-03 16:21
Just me or is that hacky solution of a workaround extremely far-fetched? I mean... C'mon! I have a bunch of Windows images which are supposed to work and yet a workaround to use the Media Creation Tool, download an image of the same version, unpack the iso, change files, use dism, not use a long-term support channel version etc. *really* considered a __ **solution** __ to this issue?!

**Comment by jamesnhan** [comment] 2020-06-08 16:53
None of the workarounds work. Attempting to download the ISO using the MediaCreationTool1903.exe command given above by @supersankary does not work anymore. You are just prompted to download the latest version of the Media Creation Tool. I also have no option to change any language settings in the VLSC, so I can't test downloading a different language, which I think would cause other issues anyway. Namely being able to _read the other language_.

I even tested the Evaluation ISO, and that does not work either.

As it stands, if you don't already have this very specific ISO, you can't do this. It's absolutely ridiculous that this issue has been open for 3 months and the assigned MS employee removed their assignment without fixing this issue.

**Comment by b0bbyB** [comment] 2020-07-01 11:37
Still an issue - discovered in March and now it's July. 
"Your Windows installation media is version 10.0.19041.329. Your SRSv2 kit requires version 10.0.18362.356."

**Comment by scanum** [comment] 2020-07-02 16:53
@Reeced40

**Comment by Reeced40** [comment] 2020-07-07 08:14
@dstrome do you have any updates yet?

**Comment by CojakSilverBack** [comment] 2020-07-14 17:38
also having this issue.

**Comment by KristoferOlafsson** [comment] 2020-07-23 13:59
This is a bit ridiculous to be that specific on the version needed... i don't have 10.0.18362.356. 

Your Windows installation media is version 10.0.18362.30. Your SRSv2 kit requires version 10.0.18362.356.
Your Windows installation media is version 10.0.18362.418. Your SRSv2 kit requires version 10.0.18362.356.

**Comment by iamalexmang** [comment] 2020-07-23 14:01
Specific is an understatement, especially under the consideration that we've raised this issue over 4 months ago...
I'd love to know how else we can help - I've already tested literally every single imaged version available available through VLSC, MPN and Visual Studio subscribers. That over a dozen various versions with no luck.

**Comment by KristoferOlafsson** [comment] 2020-07-23 14:14
ok. so. i got it to work with this image in VLSC " SW_DVD9_Win_Pro_10_1903.1_64BIT_English_Pro_Ent_EDU_N_MLF_X22-14064.ISO "   listed as "Windows 10, version 1903 (updated Sept 2019) 64-bit English"

**Comment by Reeced40** [comment] 2020-07-23 14:18
@dstrome Please assist.

**Comment by KristoferOlafsson** [comment] 2020-07-23 15:08
I believe updating line 247 to this and it should work. as long as it's a 1903 image.   if ($img.Version.substring(0,11) -ne $KitOsRequired.substring(0,11))

**Comment by Goibs** [comment] 2020-07-27 13:07
@KristoferOlafsson updating the script works and allows you to use a different version of Windows, but editing the script does not work. The install media gets successfully created, but once you attempt to actually run the setup, you get an error saying "Windows could not apply unattend settings during pass [offlineServicing]" and cancels the installation

**Comment by KristoferOlafsson** [comment] 2020-07-28 18:16
> @KristoferOlafsson updating the script works and allows you to use a different version of Windows, but editing the script does not work. The install media gets successfully created, but once you attempt to actually run the setup, you get an error saying "Windows could not apply unattend settings during pass [offlineServicing]" and cancels the installation

Interesting! thanks for testing that.

**Comment by dstrome** [comment] 2020-08-03 17:19
hi everyone. I sincerely apologize for the delay in resolving this issue. I've sent another request to the product team to determine why this is happening and what the resolution is.

**Comment by dstrome** [comment] 2020-08-03 17:49
hi everyone,

The product team has updated the script to Windows 10 1909 image we released last week. If you continue to have difficulty, please contact Microsoft Support for further assistance.

**Closed by dstrome** 2020-08-03 17:49 UTC

**Comment by ttheill** [comment] 2020-08-04 06:57
I have downloaded  SW_DVD9_Win_Pro_10_1903.1_64BIT_English_Pro_Ent_EDU_N_MLF_X22-14064.ISO however when I run the script today it says "Please enter the path to the root of your Windows install media: e:\srs\1903.1
Your Windows installation media is version 10.0.18362.356. Your SRSv2 kit requires version 10.0.18362.418.
Where can I find the right ISO?

**Comment by dstrome** [comment] 2020-08-05 21:50
hi @ttheill - I checked with our product team and it appears that the required build had to be taken down temporarily. They're working on getting a new build online as soon as possible but I don't have an estimate for that yet. It may unfortunately take several days to resolve the issue. I'm terribly sorry for the inconvenience.

**Comment by sillysampiper** [comment] 2020-08-10 03:47
Hi @dstrome 

Hoping for some clarity / a solution for deploying a MTR console from the latest CreateSrsMedia.ps1 script.

- What version of Windows 10 Enterprise is required for both the the Windows 10 machine used to create the Microsoft Teams Rooms installation media, and the Windows 10 media that will be used to deploy the MTR console onto the required 32GB USB / storage? 

As of today [the current script](https://go.microsoft.com/fwlink/?linkid=867842) (listed as Version 1.6.0) is bounces back with this message: **_This deployment kit is built for Windows Build 10.0.18362.418_**.

I'm using **_SW_DVD9_Win_Pro_10_1909.4_64BIT_English_Pro_Ent_EDU_N_MLF_X22-28609_** from **VLSC** on both the  **Windows 10 machine used to create the Microsoft Teams Rooms installation media** and the **Windows 10 media that will be used to deploy the MTR console**.

On the Configure a [Microsoft Teams Rooms console](https://docs.microsoft.com/en-us/microsoftteams/rooms/console#prepare-the-installation-media) page it shows:

_The Windows 10 machine used to create the Microsoft Teams Rooms installation media must be on the same or later version of Windows as the target installation media._

**SW_DVD9_Win_Pro_10_1909.4_64BIT_English_Pro_Ent_EDU_N_MLF_X22-28609** is Windows Build 10.0.18362.778 (latest version of 1909 on Microsoft Volume Licensing).

**Comment by RytisGrig** [comment] 2020-08-12 06:34
> 
> 
> hi @ttheill - I checked with our product team and it appears that the required build had to be taken down temporarily. They're working on getting a new build online as soon as possible but I don't have an estimate for that yet. It may unfortunately take several days to resolve the issue. I'm terribly sorry for the inconvenience.

Dear @dstrome, do you have any updated information regarding this issue?
It is really nightmare we can not upgrade our rooms and really waiting for script fixing

![image](https://user-images.githubusercontent.com/69571624/89982800-07521a80-dc7f-11ea-9c3f-33994f337c09.png)

**Comment by henhof** [comment] 2020-08-17 15:37
Hi, I have tried also on different ways with a newer Win 10 Ent. or older versions but does not work. Every time they told me to specify a valid Version. In every test, both the Client and the install medium was the same version.
- SW_DVD9_Win_Pro_10_1909_64BIT_English_Pro_Ent_EDU_N_MLF_X22-17395
- SW_DVD9_Win_Pro_10_1909.6_64BIT_English_Pro_Ent_EDU_N_MLF_X22-32299
- SW_DVD9_Win_Pro_10_1903.1_64BIT_English_Pro_Ent_EDU_N_MLF_X22-14064

@dstrome , could you please re-open the issue, since it is not fixed yet. When can upload the product team the correct version or when will the script be fixed to run with newer versions?

**Comment by njackson-matrix** [comment] 2020-08-18 00:47
We are also having this issue while trying to repair a Logitech SmartDock solution. Can either the correct version of the installation media be made available or the CreateSRSMedia script be updated to work with the version that is available please? The location we're working on has this single conference room that is down until we can get this done.

**Comment by lucderheld** [comment] 2020-08-18 10:18
I managed to get the Right Version.
I am using:

SRSDeploymentKit-4.5.35.0.msi 
with 
SW_DVD9_Win_Pro_10_1909_64BIT_German_Pro_Ent_EDU_N_MLF_X22-17400 

which is listed as "Windows 10 Enterprise Version 1909 (released NOV 2019)" in the Microsoft Partner Center. 
If someone want, I could upload both files somewhere.

**Comment by RytisGrig** [comment] 2020-08-18 10:22
Does this mean, that after implementation we will have German version interface for Teams Room?

**Comment by henhof** [comment] 2020-08-18 10:45
@lucderheld  Did has the parent system, where do you create the install media the same version?

**Comment by RytisGrig** [comment] 2020-08-18 10:48
Sorry what do you mean parent media, operating system of my computer? then no it is not

**Comment by lucderheld** [comment] 2020-08-18 15:37
Hi @henhof , @RytisGrig I updated my post:
- I used Windows 10 Enterprise 20.04 to create the media
- I think it will work with english media too. But if i remember correctly I was asked for the languange during teams setup.

**Comment by RytisGrig** [comment] 2020-08-19 06:55
> 
> 
> Hi @henhof , @RytisGrig I updated my post:
> 
>     * I used Windows 10 Enterprise 20.04 as host to create the media and used SW_DVD9_Win_Pro_10_1909_64BIT_German_Pro_Ent_EDU_N_MLF_X22-17400.iso when aked for the installation source files.
> 
>     * I think it will work with english media too. But if i remember correctly I was asked for the languange during teams setup.

OK this really works, I successfully passed media creation process with mentioned German win installation, now I will try installation of Teams Rooms, and will find out what will be language of windows :) many thanks for information sharing

**Comment by henhof** [comment] 2020-08-19 13:58
> 
> 
> > Hi @henhof , @RytisGrig I updated my post:
> > ```
> > * I used Windows 10 Enterprise 20.04 as host to create the media and used SW_DVD9_Win_Pro_10_1909_64BIT_German_Pro_Ent_EDU_N_MLF_X22-17400.iso when aked for the installation source files.
> > 
> > * I think it will work with english media too. But if i remember correctly I was asked for the languange during teams setup.
> > ```
> 
> OK this really works, I successfully passed media creation process with mentioned German win installation, now I will try installation of Teams Rooms, and will find out what will be language of windows :) many thanks for information sharing

Hi, it worked for me as well and I passed the media creation process too, with Windows 10 Enterprise 20.04 (Build 19041.388) as host and the follow details:

- SRSDeploymentKit-4.5.37.0msi and
- SW_DVD9_Win_Pro_10_1909_64BIT_English_Pro_Ent_EDU_N_MLF_X22-17395.ISO (Build 18362.418) or
- SW_DVD9_Win_Pro_10_1909_64BIT_German_Pro_Ent_EDU_N_MLF_X22-17400.ISO (Build 18362.418)

Higher versions or Builds of Windows 10 Enterprise does not work!
- SW_DVD9_Win_Pro_10_1909.6_64BIT_English_Pro_Ent_EDU_N_MLF_X22-32299.ISO (Build 18362.959)
- SW_DVD9_Win_Pro_10_2004.2_64BIT_English_Pro_Ent_EDU_N_MLF_-2_X22-32971.ISO (Build 19041.388)

**Comment by dstrome** [comment] 2020-08-19 18:51
hi everyone,

I checked with the product team and the download that contains the correct Windows version is "Windows 10, version 1909 (released Nov 2019)"

Please let me know if that works or if you are still encountering difficulties.

**Comment by glenlewisdd** [comment] 2020-08-24 18:14
Just go into the folder SRSV2\Skype Room System Deployment Kit\AutoUnattend.xml, change the build from the version="10.0.18362.xxx" to your version.  Make sure the version you have is 10.0.18362.xxx otherwise you will have issues.  

When the script is in process, you will see the folder when it ask for the driver pack you need.  

Or I just modified the PS script to set the required version to your exact version.  

Line 169 I added It is the Function Test-OsPath.
if ($KitOsRequired -eq "10.0.18362.418") {
	$KitOsRequired = "10.0.18362.356"   <# put your version you have here #>
}

**Comment by andersidahl** [comment] 2020-08-28 14:25
> hi everyone,
> 
> I checked with the product team and the download that contains the correct Windows version is "Windows 10, version 1909 (released Nov 2019)"
> 
> Please let me know if that works or if you are still encountering difficulties.

This is ridiculous! Only 1909 released Dec 2019 and later are available in the Microsoft Visual Studio portal at least.

Even with glenlewisdd good suggestion this does not seem to work... Still getting the "Windows could not apply unattend settings during pass [offlineServicing]".

**Comment by jamesnhan** [comment] 2020-08-28 17:38
So 3 months ago, I was trying to work on this for a client. Several MS tickets and finding this GitHub issue did not help. I was finally able to find an ESD file and used a decryption tool to convert the ESD file to an ISO.

The ESD file can be found here: http://dl.delivery.mp.microsoft.com/filestreamingservice/files/6561740d-e542-478c-9fd7-85281d08573e/18362.356.190909-1636.19h1_release_svc_refresh_CLIENTBUSINESS_VOL_x64FRE_en-us.esd

I don't know the legalities of the decryption tool, so I won't post it. Those with good Google Fu will be able to find it no problem based on the words I've used here.

That being said, if you can't find a way to decrypt the ESD to an ISO file, here is a copy of the ISO I made to install the Teams Room Console for our client from 3 months ago: http://dl.delivery.mp.microsoft.com/filestreamingservice/files/6561740d-e542-478c-9fd7-85281d08573e/18362.356.190909-1636.19h1_release_svc_refresh_CLIENTBUSINESS_VOL_x64FRE_en-us.esd

Download at your own risk. I take no responsibility for anything that can come from this file. If you are worried, use the ESD and decrypt it yourself. That link is directly distributed from Microsoft. Why this link can't be found anywhere else, I have no clue. I found it using a Windows 10 ISO Downloader Tool.

**Comment by IdarkbondI** [comment] 2020-09-29 21:14
For anyone that is still having this issue...you can get around this by doing the following:
**DISCLAIMER: This is not recommended or supported. Therefore use at your own risk!**

1. Open the CreateSRSMedia.ps1 file
2. Find in the code where it says:

`if ($img.Version -ne $KitOsRequired)`

3. Change it to:

`if ($img.Version -eq $KitOsRequired)`

**Comment by jamesnhan** [comment] 2020-10-15 23:05
@IdarkbondI That doesn't work. I tried it above in my [earlier comment](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/4181#issuecomment-640748218).

It will successfully create the install media, but the installation itself will fail if you don't have the correct image version.

**Comment by trub123** [comment] 2020-11-15 21:51
@lucderheld I am desperate to get hold of the SRS deployment file that you mentioned in this chat SRSDeploymentKit-4.5.35.0.msi do you still have it as Microsoft updates their latest version and so limits the ability to build to a previous "stable" revision?

**Comment by trub123** [comment] 2020-11-16 11:18
> > > Hi @henhof , @RytisGrig I updated my post:
> > > ```
> > > * I used Windows 10 Enterprise 20.04 as host to create the media and used SW_DVD9_Win_Pro_10_1909_64BIT_German_Pro_Ent_EDU_N_MLF_X22-17400.iso when aked for the installation source files.
> > > 
> > > * I think it will work with english media too. But if i remember correctly I was asked for the languange during teams setup.
> > > ```
> > 
> > 
> > OK this really works, I successfully passed media creation process with mentioned German win installation, now I will try installation of Teams Rooms, and will find out what will be language of windows :) many thanks for information sharing
> 
> Hi, it worked for me as well and I passed the media creation process too, with Windows 10 Enterprise 20.04 (Build 19041.388) as host and the follow details:
> 
> * SRSDeploymentKit-4.5.37.0msi and
> * SW_DVD9_Win_Pro_10_1909_64BIT_English_Pro_Ent_EDU_N_MLF_X22-17395.ISO (Build 18362.418) or
> * SW_DVD9_Win_Pro_10_1909_64BIT_German_Pro_Ent_EDU_N_MLF_X22-17400.ISO (Build 18362.418)
> 
> Higher versions or Builds of Windows 10 Enterprise does not work!
> 
> * SW_DVD9_Win_Pro_10_1909.6_64BIT_English_Pro_Ent_EDU_N_MLF_X22-32299.ISO (Build 18362.959)
> * SW_DVD9_Win_Pro_10_2004.2_64BIT_English_Pro_Ent_EDU_N_MLF_-2_X22-32971.ISO (Build 19041.388)

You wouldn't have a copy still of the SRSDeploymentKit-4.5.37.0.msi file would you? I need to go back to this version and Microsoft only publishes the latest version which is causing issues in my user base.

**Comment by eitan203** [comment] 2020-12-01 21:27
Hi !
I have this issue when trying to create a console installation : Your Windows installation media is version 10.0.17763.316. Your SRSv2 kit requires version 10.0.18362.418

Can someone assist ?

**Comment by gautam2009live** [comment] 2020-12-24 22:00
> > > > Hi @henhof , @RytisGrig I updated my post:
> > > > ```
> > > > * I used Windows 10 Enterprise 20.04 as host to create the media and used SW_DVD9_Win_Pro_10_1909_64BIT_German_Pro_Ent_EDU_N_MLF_X22-17400.iso when aked for the installation source files.
> > > > 
> > > > * I think it will work with english media too. But if i remember correctly I was asked for the languange during teams setup.
> > > > ```
> > > 
> > > 
> > > OK this really works, I successfully passed media creation process with mentioned German win installation, now I will try installation of Teams Rooms, and will find out what will be language of windows :) many thanks for information sharing
> > 
> > 
> > Hi, it worked for me as well and I passed the media creation process too, with Windows 10 Enterprise 20.04 (Build 19041.388) as host and the follow details:
> > 
> > * SRSDeploymentKit-4.5.37.0msi and
> > * SW_DVD9_Win_Pro_10_1909_64BIT_English_Pro_Ent_EDU_N_MLF_X22-17395.ISO (Build 18362.418) or
> > * SW_DVD9_Win_Pro_10_1909_64BIT_German_Pro_Ent_EDU_N_MLF_X22-17400.ISO (Build 18362.418)
> > 
> > Higher versions or Builds of Windows 10 Enterprise does not work!
> > 
> > * SW_DVD9_Win_Pro_10_1909.6_64BIT_English_Pro_Ent_EDU_N_MLF_X22-32299.ISO (Build 18362.959)
> > * SW_DVD9_Win_Pro_10_2004.2_64BIT_English_Pro_Ent_EDU_N_MLF_-2_X22-32971.ISO (Build 19041.388)
> 
> You wouldn't have a copy still of the SRSDeploymentKit-4.5.37.0.msi file would you? I need to go back to this version and Microsoft only publishes the latest version which is causing issues in my user base.



> > > > Hi @henhof , @RytisGrig I updated my post:
> > > > ```
> > > > * I used Windows 10 Enterprise 20.04 as host to create the media and used SW_DVD9_Win_Pro_10_1909_64BIT_German_Pro_Ent_EDU_N_MLF_X22-17400.iso when aked for the installation source files.
> > > > 
> > > > * I think it will work with english media too. But if i remember correctly I was asked for the languange during teams setup.
> > > > ```
> > > 
> > > 
> > > OK this really works, I successfully passed media creation process with mentioned German win installation, now I will try installation of Teams Rooms, and will find out what will be language of windows :) many thanks for information sharing
> > 
> > 
> > Hi, it worked for me as well and I passed the media creation process too, with Windows 10 Enterprise 20.04 (Build 19041.388) as host and the follow details:
> > 
> > * SRSDeploymentKit-4.5.37.0msi and
> > * SW_DVD9_Win_Pro_10_1909_64BIT_English_Pro_Ent_EDU_N_MLF_X22-17395.ISO (Build 18362.418) or
> > * SW_DVD9_Win_Pro_10_1909_64BIT_German_Pro_Ent_EDU_N_MLF_X22-17400.ISO (Build 18362.418)
> > 
> > Higher versions or Builds of Windows 10 Enterprise does not work!
> > 
> > * SW_DVD9_Win_Pro_10_1909.6_64BIT_English_Pro_Ent_EDU_N_MLF_X22-32299.ISO (Build 18362.959)
> > * SW_DVD9_Win_Pro_10_2004.2_64BIT_English_Pro_Ent_EDU_N_MLF_-2_X22-32971.ISO (Build 19041.388)
> 
> You wouldn't have a copy still of the SRSDeploymentKit-4.5.37.0.msi file would you? I need to go back to this version and Microsoft only publishes the latest version which is causing issues in my user base.

@trub123  Hello, it will be a great help if you can upload and share SW_DVD9_Win_Pro_10_1909_64BIT_English_Pro_Ent_EDU_N_MLF_X22-17395.ISO (Build 18362.418) via google drive, Unable to find this version anywhere.
