### ISSUE TITLE
Repo links to empty repo

### ISSUE THREAD

**Issue by taikedz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9822] opened 2023-03-16 09:13 UTC
There is a 404 for Linux deb package. This has been known[ for weeks now][forum].

The repo links on the [install instructions][install-notes] page point to empty packages

[All `Packages` files are 0 bytes in length (empty)][repo-url]

As a result, Teams is uninstallable from repo

[forum]: https://techcommunity.microsoft.com/t5/microsoft-teams-free/deb-package-not-found-404/m-p/3752685
[install-notes]: https://learn.microsoft.com/en-us/microsoftteams/get-clients?tabs=Linux
[repo-url]: https://packages.microsoft.com/repos/ms-teams/dists/stable/main/

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0c86f401-cff4-93b3-ff69-b9787a87e644
* Version Independent ID: c0808bd3-cf63-0625-4c3c-65469c26fb3e
* Content: [Get clients for Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/get-clients?tabs=Windows)
* Content Source: [Teams/get-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-clients.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by get-itips** [comment] 2023-03-29 21:23
Duplicate of https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9772

**Closed by get-itips** 2023-03-29 21:23 UTC
Labels: doc-bug
