### ISSUE TITLE
List of available rate centres in Canada?

### ISSUE THREAD

**Issue by the-hutch** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3895] opened 2020-02-03 17:30 UTC
How about adding a list of rate centres for Canada and US that are available? That would help us all understand if this service is viable for our enterprises. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ddf1c3c-7fb9-ff3c-e8cd-af75999c78cb
* Version Independent ID: 6178c672-003f-8f99-f4ab-cf9b06cf5ede
* Content: [Contact the PSTN service desk - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/manage-phone-numbers-for-your-organization/contact-pstn-service-desk#feedback)
* Content Source: [Teams/manage-phone-numbers-for-your-organization/contact-pstn-service-desk.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-phone-numbers-for-your-organization/contact-pstn-service-desk.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment] 2020-02-04 18:39
@the-hutch  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment] 2020-02-12 07:51
@tonysmit is it possible to have this information added to the article?

**Comment by tonysmit** [comment] 2020-02-28 08:32
@CarolynRowe - you should check with Dave Lickorish about this. @LanaChin - did you do an article about Canadian Rate Centers for Dave a while back. I can't find it in the TOC anywhere.

**Comment by LanaChin** [comment] 2020-03-12 14:28
@Tonysmit - I don't recall doing or updating an article on Canadian rate centers.

**Comment by tonysmit** [comment] 2020-03-30 22:52
@scanum - I pinged a PM. Let's see what he says.

**Comment by tonysmit** [comment] 2020-03-31 16:00
@the-hutch - I'm working with the PM on this. The issue is it's a bit complex. There are rate centers that are supported now and of course ones coming on line all the time. He has a resource, but he needs to get approval for us to post it publically. Stay tuned.

**Comment by the-hutch** [comment] 2020-03-31 17:12
Wahoo! Thanks :)

**Comment by tonysmit** [comment] 2020-04-02 19:32
@the-hutch - We got approval! I'm going to create a task for our vendor @LanaChin to create a downloadable XLS. I don't have a URL for it right this minute. I'm going to close this, but please ping me in the next week or so to remind me to send you the URL when we get it published. Here is my MSFT email: tony.smith@microsoft.com in case.

**Closed by tonysmit** 2020-04-02 19:32 UTC
