### ISSUE TITLE
German Translation for Skype for Business Surface Hub is pretty bad.

### ISSUE THREAD

**Issue by renatewi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#680] opened 2018-08-17 12:24 UTC
https://docs.microsoft.com/de-de/SkypeForBusiness/plan-your-deployment/clients-and-devices/clients-and-devices
One of the Titles in the German translation is:
Skype für Unternehmen auf Fläche Hub
This Group of Words is bad and has no Meaning.
Proper Names should not be translated. It shpould Read:
"Skype for Business auf Surface Hub"

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 7699cfdd-d76c-744c-cc49-80215adfb51b
* Version Independent ID: 539a1447-b159-aaf8-20f2-bb95d839286a
* Content: [Planen für Clients und Geräte](https://docs.microsoft.com/de-de/SkypeForBusiness/plan-your-deployment/clients-and-devices/clients-and-devices)
* Content Source: [Skype/SfbServer/plan-your-deployment/clients-and-devices/clients-and-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr.de-DE/blob/live-sxs/Skype/SfbServer/plan-your-deployment/clients-and-devices/clients-and-devices.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @PhillipGarding
* Microsoft Alias: **jambirk**

**Comment by samanthaw** [comment] 2018-08-27 17:47
@renatewi @jambirk we've fixed the German translation

**Comment by renatewi** [comment] 2018-08-28 18:48
thanks

**Comment by jambirk** [comment] 2018-08-29 16:26
Closing this issue now, @renatewi  please let us know if the issue isn't resolved in your opinion.

**Comment by renatewi** [comment] 2018-08-29 18:07
Thanks, the new text is much better 😊

**Closed** 2018-08-29 18:15 UTC
Labels: Skype for Business Server
