### ISSUE TITLE
The download link is not working

### ISSUE THREAD

**Issue by CarlosFarrica** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3147] opened 2019-10-03 11:52 UTC
[The download link is not working 
  
 
https://www.microsoft.com/en-us/download/details.aspx?id=39366]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27364aed-dc10-dcaf-8446-bc93e39bd4ca
* Version Independent ID: 907a29a6-6ff3-5c91-5c74-cf98cf71ad88
* Content: [Download and install the Skype for Business Online Connector module](https://docs.microsoft.com/en-us/skypeforbusiness/set-up-your-computer-for-windows-powershell/download-and-install-the-skype-for-business-online-connector)
* Content Source: [Skype/SfbOnline/set-up-your-computer-for-windows-powershell/download-and-install-the-skype-for-business-online-connector.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/set-up-your-computer-for-windows-powershell/download-and-install-the-skype-for-business-online-connector.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by leebjn** [comment] 2019-10-03 14:06
Download link is not working for me either. Just used it 2 days ago and it worked fine.

**Comment by jambirk** [comment] 2019-10-03 16:23
@CarlosFarrica  and  @leebjn 

The link shown in the comment does fail, but it appears to be doing so because of the square bracket appended at the end. I'm not able to reproduce this in the article itself. 

This download center asset was updated yesterday, or possibly early this morning. When one of these assets is updated, there is a "freeze" period of several hours, and during that time the asset page is unavailable. It's back to normal now.

@tonysmit closing this now on your behalf.

**Closed by jambirk** 2019-10-03 16:23 UTC
