### ISSUE TITLE
Chrome and Edge is still not "fully" supported

### ISSUE THREAD

**Issue by TomoharuMisawa** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3569] opened 2019-12-07 06:40 UTC
Check box to share system audio when sharing screen is not implemented.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Microsoft Teams の制限事項と仕様 - Microsoft Teams](https://docs.microsoft.com/ja-jp/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment] 2019-12-09 06:58
@TomoharuMisawa Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment] 2020-01-04 01:54
@TomoharuMisawa Thank you for raising this issue! I'll be looking into it!

**Comment by TokyoScarab** [comment] 2020-02-27 10:32
@scanum Would we be able to get the Japanese language team to assist with this issue?

**Comment by scanum** [comment] 2020-03-12 01:38
@officeglobal Hi! Could you please help with this issue? Thank!

**Comment by OfficeGlobal** [comment] 2020-03-17 13:32
@TomoharuMisawa I'm not sure what is exactly wrong, is the trouble with translation or the issue is in source (en-us) article related to Chrome support?

Thank you

**Comment by TomoharuMisawa** [comment] 2020-03-17 17:14
The browser support table states that Chrome is fully supported, but isn't the system audio output supported by the browser?

**Comment by TokyoScarab** [comment] 2020-03-31 20:33
@TomoharuMisawa The audio from Chrome should be working as intended. Have you tried checking what audio settings you have set in the Teams application? The problem could lie there or perhaps by checking the audio settings in Windows to make sure nothing is conflicting with the default system audio. Could you tell me a little more about your setup?

**Comment by scanum** [comment] 2020-04-08 05:32
@TomoharuMisawa We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Closed by scanum** 2020-04-08 05:32 UTC

**Comment by TomoharuMisawa** [comment] 2020-04-08 16:28
Please give me System Audio Output Settings Capture at Chrome...
