### ISSUE TITLE
Links to pricing are not informative

### ISSUE THREAD

**Issue by MadCabbage** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#693] opened 2018-08-22 09:38 UTC
I would love to find out what the pricing costs, but it only points me to the generic Office 365 pricing, which does not show calling plan prices.
I would also love to know if the minutes per user per month are pooled across all  users, but there is nothing here to tell me that.. :-(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d29f845-f27d-56f7-5f63-4952e4048680
* Version Independent ID: c31bb4ad-902a-2e58-0f36-e0f00da76668
* Content: [Skype for Business and Microsoft Teams add-on licensing](https://docs.microsoft.com/en-us/SkypeForBusiness/skype-for-business-and-microsoft-teams-add-on-licensing/skype-for-business-and-microsoft-teams-add-on-licensing)
* Content Source: [Skype/SfbOnline/skype-for-business-and-microsoft-teams-add-on-licensing/skype-for-business-and-microsoft-teams-add-on-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/skype-for-business-and-microsoft-teams-add-on-licensing/skype-for-business-and-microsoft-teams-add-on-licensing.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by AndreaBarr** [comment] 2018-09-13 17:50
@MadCabbage Thank you for this feedback

We want to make sure all the pricing information is included in the documents. I am goin to send this to the Teams team so we can get this added approprialty. 

I was able to get this into the backlog for the Teams team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by tonysmit** [comment] 2019-01-25 18:12
@MadCabbage - I have an email thread with Andrea so she can update the text. The issue is that this information is buried at the bottom of the page right before the FAQs. I've also contacted marketing to see if we can get the pricing information elevated in the future. I hope this helps. Thanks, Tony  @AndreaBarr - can you add some text to the page in question telling customers it's at the bottom of the page until I can get marketing to respond to my request please? Thanks.

**Comment by MadCabbage** [comment] 2019-01-28 12:04
Hi Tony,
Many thanks for following this up - thanks for pointing out where the information is.  I note the table provides calling plan costs in GBP & USD, but the main costs are only shown in USD?

Please advise..

**Comment by scanum** [comment] 2019-03-29 18:57
@tonysmit and @AndreaBarr any updates to this issue? Thanks!

**Comment by scanum** [comment] 2019-05-03 17:45
@tonysmit and @AndreaBarr any updates to this issue? Thanks!

**Comment by tonysmit** [comment] 2019-05-03 19:30
@scanum AND @AndreaBarr - Here are the bookmarked links that I worked with marketing to resolve this issue. Please save these for future reference. There are other topics out there that have generic links that should be replaced by these:

**Audio Conferencing (was PSTN Conferencing)**
https://products.office.com/en-us/microsoft-teams/online-meeting-solutions#pricing
https://go.microsoft.com/fwlink/?linkid=799762
 
**Phone System (was Cloud PBX)**
https://products.office.com/en-us/microsoft-teams/voice-calling#pricing 
https://go.microsoft.com/fwlink/?linkid=799763

**Calling Plans (was PSTN Calling)**
https://products.office.com/en-us/microsoft-teams/voice-calling#pricing 
https://go.microsoft.com/fwlink/?linkid=799761

**Comment by tonysmit** [comment] 2019-05-03 19:31
Sorry, I forgot to follow up on this. Closing now.

**Closed by tonysmit** 2019-05-03 19:30 UTC
Labels: Skype for Business Online
