### ISSUE TITLE
Incorrect Link

### ISSUE THREAD

**Issue by Krakass** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10531] opened 2023-10-30 01:05 UTC
Step 2. at https://learn.microsoft.com/en-us/microsoftteams/new-teams-vdi-requirements-deploy#option-1-uninstall-the-classic-teams-client-and-install-the-new-one links to "Hardware and software requirements for SharePoint Server 2016" instead of the MSIX for the new version of Teams.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: db74252a-f531-8fcf-4da0-5e439cfdfd8d
* Version Independent ID: db74252a-f531-8fcf-4da0-5e439cfdfd8d
* Content: [New Microsoft Teams for Virtualized Desktop Infrastructure (VDI) - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/new-teams-vdi-requirements-deploy)
* Content Source: [Teams/new-teams-vdi-requirements-deploy.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/new-teams-vdi-requirements-deploy.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment] 2023-10-30 16:05
Duplicate of https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/10530

**Comment by get-itips** [comment] 2023-10-31 20:27
Fixed in https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/5e1aff2bd9bb8f4227b20c1f4dfb2ba6034823b9

**Closed by get-itips** 2023-10-31 20:27 UTC
Labels: doc-bug
