### ISSUE TITLE
Please share the step by step details to enable teams automatic reocrding 

### ISSUE THREAD

**Issue by robinpoulose1** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10586] opened 2023-11-13 12:53 UTC
Please share the step by step details to enable teams automatic reocrding 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 733c7b3e-1daa-7569-9059-c3c335262155
* Version Independent ID: 733c7b3e-1daa-7569-9059-c3c335262155
* Content: [Manage Microsoft Teams meeting recording options for sensitive meetings - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/manage-meeting-recording-options)
* Content Source: [Teams/manage-meeting-recording-options.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/manage-meeting-recording-options.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment] 2023-11-13 13:08
Duplicate of https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/10587

**Closed by MikePlumleyMSFT** 2023-11-13 13:08 UTC
