### ISSUE TITLE
Could not resolve phoneNumberType 'OCMobile'

### ISSUE THREAD

**Issue by vlethiec** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9469] opened 2022-11-07 17:30 UTC
Hi all, 

We are working on Teams Phone Mobile, but when we try to execute the cmdlet, we have the following error. 

**With TPM 4.7.0**

`PS C:\WINDOWS\system32> set-csphonenumberassignment -Identity  17e10b9c-f9fd-47f7-9791-dbd14770191b -PhoneNumber +33662105560 -PhoneNumberType OCMobile
Microsoft.Teams.ConfigAPI.Cmdlets.internal\Set-CsPhoneNumberAssignment : Could not resolve phoneNumberType 'OCMobile'. Available phoneNumberType values are 'DirectRouting', 'CallingPlan', 'OperatorConnect'.
At C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\4.7.0\custom\Merged_custom_PsExt.ps1:1298 char:13`

**With TPM 4.9.0**

`set-csphonenumberassignment -Identity  17e10b9c-f9fd-47f7-9791-dbd14770191b -PhoneNumber +33662105560 -PhoneNumberType OCMobile
Microsoft.Teams.ConfigAPI.Cmdlets.internal\Set-CsPhoneNumberAssignment : Could not resolve phoneNumberType 'OCMobile'. Available phoneNumberType values are 'DirectRouting', 'CallingPlan', 'OperatorConnect'.
At C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\4.9.0\custom\Merged_custom_PsExt.ps1:1298 char:13`

Do we need to active something to get the 'OCMobile' type working?
I didn't activate Operator Connect and Calling Plan, but they are available in the cmdlet nevertheless. 

If it is not available in the GA modules, I think you should precise this point in the documentation. 

Best regards, 

Vincent

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 69c67496-cace-f833-7cfc-dca7722fef3e
* Version Independent ID: 5a14f81c-529c-4971-5ce8-39633834d4d3
* Content: [Assign, change, or remove a phone number for a user - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/assign-change-or-remove-a-phone-number-for-a-user)
* Content Source: [Teams/assign-change-or-remove-a-phone-number-for-a-user.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/assign-change-or-remove-a-phone-number-for-a-user.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by vlethiec** [comment] 2022-11-08 09:34
The issue has already opened here #9438, but no answer yet.

**Comment by scanum** [comment] 2022-11-13 02:40
Duplicate of #9438

**Closed by scanum** 2022-11-13 02:40 UTC
