### ISSUE TITLE
Unclear documentation about Approvals history retention

### ISSUE THREAD

**Issue by KhisteMahesh** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10367] opened 2023-09-06 07:41 UTC
[Enter feedback here]
https://learn.microsoft.com/en-us/microsoftteams/approval-admin#retention-policy
It unclear that for how many days Approvals history is available to users ?It mentions that its stored in Dataverse and Forms database but retention duration is unclear.
I would suggest better clarification on following topics would help users and admins:
Approvals responses data retention , Approval custom templates retention, Approvals history shown in Approvals hub and Approvals flow retention ( for ex Approval is sent to a person and if that person doesn't approve in 30 days , will that flow be still available after that or broke / error out , what error will be showed ?)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 055b01ff-ee6c-7d5a-74bd-0e8eed7ee6b5
* Version Independent ID: 13c4174f-2a2a-2ef9-14c5-2f10817cc66a
* Content: [Manage the Approvals app in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/approval-admin)
* Content Source: [Teams/approval-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/approval-admin.md)
* Service: **msteams**
* GitHub Login: @Lana-Chin
* Microsoft Alias: **v-chinlana**

**Comment by get-itips** [comment] 2023-09-08 18:57
Duplicate of https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/10366

**Closed by get-itips** 2023-09-08 18:57 UTC
Labels: doc-bug
