### ISSUE TITLE
correction in table 1a and 1c 

### ISSUE THREAD

**Issue by Sanjeev017** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7434] opened 2021-06-18 13:38 UTC
Table 1a: in-tenant new chat or call routing to an islands mode recipient
when the originator is on-prem using Teams client then recipient with Teams client(islands mode) should work which is shown as not possible in the article

Table 1c: in-tenant new chat or call routing to a TeamsOnly mode recipient
when the originator is with Teams on-prem and the recipient is Teamsonly mode then it should also work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 169a20a6-ebf7-1093-3cb1-fb438b9b7e13
* Version Independent ID: b2074fd8-724e-75fa-bafb-a0f7966bf593
* Content: [Coexistence with Skype for Business - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/coexistence-chat-calls-presence)
* Content Source: [Teams/coexistence-chat-calls-presence.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/coexistence-chat-calls-presence.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by dariomws** [comment] 2021-06-21 09:48
Hi @Sanjeev017, thank you for your feedback.

"Not possible" is correct in both cases. There is a sentence with a bit longer explanation in the article:
"If the Skype for Business account of the originator is homed on-premises, that user can't use the Teams client for in-tenant interoperability or for federation. That user can only use the Skype for Business client for interoperability and federation."

**Comment by howardzhangmsft** [comment] 2021-07-01 02:52
@dariomws  based on my testing, the 'not possible' cited in table 1a and 1c is not true. I am able to call/chat for the mentioned scenarios

**Comment by dariomws** [comment] 2021-07-01 07:27
Users homed in SfB on-premises with upgrade mode Island can chat with an external (federated) account using the Teams client?
Please double-check it, it doesn't work by design. Thanks!

**Comment by Sanjeev017** [comment] 2021-07-01 07:36
@dariomws as mentioned in the article-  **that user can't use the Teams client for in-tenant interoperability or for federation.**
I do agree with this but table 1a and 1c isn't a case of interoperability or federation. it is just Teams to Teams client scenario which don't require gateway.

**Comment by dariomws** [comment] 2021-07-01 08:54
@Sanjeev017 read the article in detail, and I agree with you now.

The following sentence is talking about **in-tenant interoperability and federation**:
"If the Skype for Business account of the originator is homed on-premises, that user can't use the Teams client for in-tenant interoperability or for federation. That user can only use the Skype for Business client for interoperability and federation."
If an sfb user is homed on-premises and upgrade mode is Island, he can't use the Teams client to communicate with an in-tenant SfBO user (SfB* upgrade mode) or federated user.

The tables show routing in all scenarios, not just interoperability.

This was incorrectly updated in March from Teams to "Not possible". Thanks a lot for noticing it.

**Comment by dariomws** [comment] 2021-07-01 09:02
@Sanjeev017 good catch, thanks!

**Comment by dariomws** [comment] 2021-08-12 10:47
@scanum this issue was handled here:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/b8cda4a377f37a2cf6c7f1147bca87185e9ccf3e#diff-ccaa1fd683a23f24a261e109bde659811359807cf406ef793d798e3b61b217c1

Please close it. Thanks!

**Closed** 2021-09-03 03:07 UTC
Labels: doc-bug
